#!/bin/zsh
log()
{
        echo $1
}
remove()
{
        ref=("01" "02" "03" "04" "05" "06" "07" "08" "09" "10" "11" "12" "13" "14" "15" "16" "17" "18" "19" "20" "21" "22" "23" "24" "25" "26" "27" "28" "29" "30")
        let "count=0"
        a=(1)
        if [ $1 -eq "1" ]
        then
                a=(2 5 7 8 11 13 14 17 20 22 23 26 )
        elif [ $1 -eq "2" ]
        then
                a=(3 9 12 15 20 24)
        elif [ $1 -eq "3" ]
        then
                a=(4 8 12 14)
        else
                a=(5 10)
        fi
        log $1
        let "val=1"
        for file in ./filepng*.png
        do
                let "got=0"
              for i in $a
              do
             # log "checking $file with index $i at index $val"
                   if [ $val -eq $i ]
                    then
                        got=1
                        log "removing $file at index $i"
                        rm $file $(echo $file | sed "s/\.png/\.txt/g" )
                        break
                   fi
              done
        if [ $got -eq "0" ]
        then
                let "count=$count+1"
                mv $file "filepng"${ref[$count]}".png"
                log "${ref[$count]}"
                mv $(echo $file | sed "s/\.png/\.txt/g" ) filepng${ref[$count]}.txt
        fi
        let "val=$val+1"
        done
}
workplz()
{
        a=$(du "$1" | sed -e "s/\s.*png//")
        if [ $a -gt "600" ]
        then
                remove 1
        elif [ $a -gt "500" ]
        then
                remove 2
        elif [ $a -gt "400" ]
        then
                remove 3
        elif [ $a -gt "300" ]
        then
                remove 4
        else
                echo "$1 already at best"
                if [ ! -f tmp.png ]
                then
                        mv $1 tmp.png
                fi
                return
        fi
        rm tmp.png
        apngasm tmp.png $(ls filepng* | tr '\n' ' ') -z0
        workplz tmp.png
}
mkdir output
for file in ./*.gif
do
        convert -compress LZW   -coalesce $file  filepng%02d.png
        newf=$(echo $file | sed -e "s/\.gif/\.png/g" )
        apngasm $newf filepng*
        workplz $newf
        mv tmp.png ./output/$(uuidgen).png
        rm filepng*
done

